---
title: "Datasheet For Mental Health Dataset"
author: "Olaedo Okpareke"
Organization: "The University of Toronto"
output: html_document
---

# Motivation

*The questions in this section are primarily intended to encourage dataset creators to clearly articulate their reasons for creating the dataset and to promote transparency about funding interests.*

1. **For what purpose was the dataset created?** 

This dataset was created to evaluate the importance of mental health to people worldwide, as well as the probability that a person seeks mental health care, dependent on their belonging to various groups.   


2. **Who created this dataset (e.g. which team, research group) and on behalf of which entity (e.g. company, institution, organization)**?

	*Your Answer Here*

This dataset was created by the Wellcome Global Monitor on behalf of the Wellcome Trust, and edited by Olaedo Okpareke of the University of Toronto. 

3. **What support was needed to make this dataset?** 

The project was funded by the Wellcome Trust. 


4. **Any other comments?**

No.

## Composition



1. **What do the instances that comprise the dataset represent (e.g. documents, photos, people, countries)?** 

Each row of the main dataset is a person, and the information about that specific person. 

2. **How many instances are there in total (of each type, if appropriate)?**

There are about 119,000 instances. 

3. **Does the dataset contain all possible instances or is it a sample (not necessarily random) of instances from a larger set?**

The dataset is a sample of the total global population. The sample is intended to be representative of the global population. This was validated by stratification of the dataset by the authors.  


4. **What data does each instance consist of?** "Raw" data (e.g. unprocessed text or images) or features? In either case, please provide a description.

Each instance consists of demographic, societal information or information on beliefs or choices. For example Age, income class, country, belief in mental health science.

5. **Is there a label or target associated with each instance?** 

Yes, there is a unique case ID for every individual. 

6. **Is any information missing from individual instances?** 

There is a lot of missing information, particularly on the choice to seek mental health. This is most likely because these questions were not asked to most respondents. 

7. **Are relationships between individual instances made explicit (e.g. users' movie ratings, social network links)?** 

Yes, through the unique ID.

8. **Are there recommended data splits (e.g. training, development/validation, testing)?** 

No.
 
9. **Are there any errors, sources of noise, or redundancies in the dataset?** 

There may be, if respondents answered untruthfully. It is difficult to tell. 


10. **Is the dataset self-contained, or does it link to or otherwise rely on external resources (e.g. websites, tweets, other datasets)?** 

It is self-contained. 

11. **Does the dataset contain data that might be considered confidential (e.g. data that is protected by legal privilege or by doctor-patient confidentiality, data that includes the content of individuals' non-public communications)?** 


Yes, the decision to seek mental health care, age, and the subjective income are examples of private information in the dataset. 



12. **Does the dataset contain data that, if viewed directly, might be offensive, insulting, threatening, or might otherwise cause anxiety?** 

No.

13. **Does the dataset relate to people?**

Yes.

14. **Does the dataset identify any subpopulations (e.g. by age, gender)?** 

Yes, age, gender, and country are examples.

15. **Is it possible to identify individuals (i.e., one or more natural persons), either directly or indirectly (i.e., in combination with other data) from the dataset?**

No. 

16. **Does the dataset contain data that might be considered sensitive in any way (e.g. data that reveals racial or ethnic origins, sexual orientations, religious beliefs, political opinions or union memberships, or locations; financial or health data; biometric or genetic data; forms of government identification, such as social security numbers; criminal history)?** 

yes, it contains political information on if the government should fund mental health research.

17. **Any other comments?**

No.


## Collection


1. **How was the data associated with each instance acquired?** Was the data directly observable (e.g. raw text, movie ratings), reported by subjects (e.g. survey responses), or indirectly inferred/derived from other data (e.g. part-of-speech tags, model-based guesses for age or language)? If data was reported by subjects or indirectly inferred/derived from other data, was the data validated/verified? If so, please describe how.

Through a telephone-based global survey.

2. **What mechanisms or procedures were used to collect the data (e.g. hardware apparatus or sensor, manual human curation, software program, software API)?**

Manual Curation.

3. **If the dataset is a sample from a larger set, what was the sampling strategy (e.g. deterministic, probabilistic with specific sampling probabilities)?**

Probability based random Sampling. 

4. **Who was involved in the data collection process (e.g. students, crowdworkers, contractors) and how were they compensated (e.g. how much were crowdworkers paid)?**

Researchers and Surveyors. Pay structure is unkown. 

5. **Over what timeframe was the data collected?** 

February 2020 to August 2021.

7. **Were any ethical review processes conducted (e.g. by an institutional review board)?** 
Yes, questions were screened for sensitivity by Gallup’s Institutional Review
Board (IRB). The process was Research and Literature Review -> Expert Interviews -> questionnaire first draft -> cognitive testing -> questionaire refinement -> pilot testing -> Final questionnaire.   

8. **Does the dataset relate to people?** If not, you may skip the remainder of the questions in this section.

Yes.

9. **Did you collect the data from the individuals in question directly, or obtain it via third parties or other sources (e.g. websites)?**

Data was gotten directly from individuals.

10. **Were the individuals in question notified about the data collection?** 

Yes, they were told that their answers would be recorded. 
Link: https://cms.wellcome.org/sites/default/files/2021-10/wgm2020-methodology.pdf

11. **Did the individuals in question consent to the collection and use of their data?** 

Yes, those who did not consent were put as "Refused" as an observation.
Link: https://cms.wellcome.org/sites/default/files/2021-10/wgm2020-methodology.pdf

12. **If consent was obtained, were the consenting individuals provided with a mechanism to revoke their consent in the future or for certain uses?** 

No. 

13. **Has an analysis of the potential impact of the dataset and its use on data subjects (e.g. a data protection impact analysis) been conducted?**

No. 

14. **Any other comments?**

No.


## Preprocessing / Cleaning / Labeling

*Dataset creators should read through these questions prior to any pre-processing, cleaning, or labeling and then provide answers once these tasks are complete. The questions in this section are intended to provide dataset consumers with the information they need to determine whether the “raw” data has been processed in ways that are compatible with their chosen tasks. For example, text that has been converted into a “bag-of-words” is not suitable for tasks involving word order.*

1. **Was any preprocessing/cleaning/labeling of the data done (e.g. discretization or bucketing, tokenization, part-of-speech tagging, SIFT feature extraction, removal of instances, processing of missing values)?** 

Yes, the data was cleaned. 

2. **Was the "raw" data saved in addition to the preprocessed/cleaned/labeled data (e.g. to support unanticipated future uses)?** 

No.

3. **Is the software used to preprocess/clean/label the instances available?** 

No. 

4. **Any other comments?**

No. 


## Uses

*These questions are intended to encourage dataset creators to reflect on the tasks  for  which  the  dataset  should  and  should  not  be  used.  By  explicitly highlighting these tasks, dataset creators can help dataset consumers to make informed decisions, thereby avoiding potential risks or harms.*

1. **Has the dataset been used for any tasks already?** 

yes, to provide more infromation on best ways to form mental health treatments.

2. **Is there a repository that links to any or all papers or systems that use the dataset?** 

No.

3. **What (other) tasks could the dataset be used for?**

Prediction of other variables such as the probability someone has felt anxious in the last 12 month. 

4. **Is there anything about the composition of the dataset or the way it was collected and preprocessed/cleaned/labeled that might impact future uses?**

No. 

5. **Are there tasks for which the dataset should not be used?** 

No.

6. **Any other comments?**

No.


## Distribution

*Dataset creators should provide answers to these questions prior to distributing the dataset either internally within the entity on behalf of which the dataset was created or externally to third parties.*

1. **Will the dataset be distributed to third parties outside of the entity (e.g. company, institution, organization) on behalf of which the dataset was created?** 

No, the dataset is only available on the website. 

2. **How will the dataset be distributed (e.g. tarball on website, API, GitHub)?** 

On the Wellcome Global Monitor Website. There is no DOI available. 

3. **When will the dataset be distributed?**

The dataset is already available. 

4. **Will the dataset be distributed under a copyright or other intellectual property (IP) license, and/or under applicable terms of use (ToU)?** 

Intellectual property of the Wellcome Trust. 
Link: https://wellcome.org/who-we-are/privacy-and-terms

5. **Have any third parties imposed IP-based or other restrictions on the data associated with the instances?** 

No. 

6. **Do any export controls or other regulatory restrictions apply to the dataset or to individual instances?** 

No. 

7. **Any other comments?**

No. 


## Maintenance

*As with the previous section, dataset creators should provide answers to these questions prior to distributing the dataset. These questions are intended to encourage dataset creators to plan for dataset maintenance and communicate this plan with dataset consumers.*

1. **Who is supporting/hosting/maintaining the dataset?**

Wellcome Trust.

2. **How can the owner/curator/manager of the dataset be contacted (e.g. email address)?**

Email address: Not stated on Website

Telephone: +44(0)2076118888


3. **Is there an erratum?** 

No. 

4. **Will the dataset be updated (e.g. to correct labeling errors, add new instances, delete instances)?** 

No, the dataset is final. 

5. **If the dataset relates to people, are there applicable limits on the retention of the data associated with the instances (e.g. were individuals in question told that their data would be retained for a fixed period of time and then deleted)?**

No, there is no limit. 


6. **Will older versions of the dataset continue to be supported/hosted/maintained?** 

Older versions (years) of the dataset are being hosted on their own webpages. 

7. **If others want to extend/augment/build on/contribute to the dataset, is there a mechanism for them to do so?** 

No. Only those employed by Wellcome Trust and Gallup Polls are approved to add on to the dataset. 

8. **Any other comments?**

No. 
